### ISSUE TITLE
Refactor: User should not be able to sign up with an already existing email

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/final-project#23]
## ✅ Task List

- [x] Update index.js to prevent duplicate inserts given the value of the inputted 'email' and throw an error when returned rows is falsy.
- [x] Update auth-form.jsx to update 'error' property of 'this.state' with an error message indicating that the email is already in use if 'result' of promise has an error property.  
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
