### ISSUE TITLE
Refactor: Implement authorization-middleware for feature, user can create a new listing

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/final-project#26]
## ✅ Task List

- [x] Update index.js to refactor post method for submitting new listing for token authorization.
- [x] Update create-listing-form-parent.jsx to refactor fetch method by adding x-access-token header with token.
- [x] Test using HTTPie.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
