### ISSUE TITLE
Refactor: Do not render 'contact seller' button for listings that belong to the user when viewed in listing-details.jsx

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/final-project#28]
## ✅ Task List

- [x] Update listing-details.jsx to add a condition statement for rendering the button depending on whether or not the listing belongs to the user.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
