### ISSUE TITLE
Design Update: Navigation & header bar / visible card style / fixed dollar symbol

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/final-project#33]
## 📐 Plan

Modify css to keep a persistent header and more easily discernible listing cards.

## 🖼️ Wireframes

![Screen Shot 2021-12-07 at 1 01 22 PM](https://user-images.githubusercontent.com/55222182/145105659-78488226-cba0-4867-a2f7-d7054f173d6b.png)
![Screen Shot 2021-12-07 at 1 02 05 PM](https://user-images.githubusercontent.com/55222182/145105673-aaa7c82f-aa30-42a2-8240-c3f95c0c4b54.png)

## ✅ Task List

- [x] Update the styling for the navbar component to include a fixed header.
- [x] Update app.jsx and navbar.jsx to dynamically set the header text to the corresponding page the user is viewing.
- [x] Update the styling for the listing cards to reflect the wireframe.
- [x] Update create-listing-form-details.jsx to include a dollar symbol in the `Price` input element.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
