### ISSUE TITLE
Feature: User can sign up.

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/final-project#6]
## ⚙️ Feature

User can sign up.

## 📐 Functionality

User can select 'Get Started' to view sign up form to register.

## 🖼️ Wireframes

(name of app subject to change)

![Screen Shot 2021-11-02 at 3 05 52 PM](https://user-images.githubusercontent.com/55222182/139958880-5f0f1b52-0948-4103-84f5-37b6ffd61ed0.png)
![Screen Shot 2021-11-02 at 3 06 13 PM](https://user-images.githubusercontent.com/55222182/139958898-8b03a87e-edc8-4faf-9c32-526dde807e0b.png)
![Screen Shot 2021-11-02 at 3 06 20 PM](https://user-images.githubusercontent.com/55222182/139958905-52fb564c-bce2-45bc-b7ac-38a327e96586.png)

![Screen Shot 2021-11-02 at 3 06 32 PM](https://user-images.githubusercontent.com/55222182/139958914-598fe38f-b092-4a3c-9124-e6f42332cb37.png)
![Screen Shot 2021-11-02 at 3 06 42 PM](https://user-images.githubusercontent.com/55222182/139958974-cca4125d-ac2e-447b-9d58-218448cd7a32.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include the post method for signing up.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the app greeting page which contains the sign up form.
- [x] Update apps.jsx to handle rendering sign up page component.
- [x] Ensure the email and hashed password is successfully inserted into the database.
- [x] Ensure the front-end resembles the wireframe.
- [x] Update component to render the sign up form upon selecting 'Get Started' button.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
